### Creates new patient entity
POST http://lb-1f353917.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe Kafka",
  "email": "kafka17@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-05-05",
  "registeredDate": "2024-11-28"
}

###